switch to herbstluftwm

diff --git a/src/.config/herbstluftwm/autostart b/src/.config/herbstluftwm/autostart
--- a/src/.config/herbstluftwm/autostart
+++ b/src/.config/herbstluftwm/autostart
@@ -1,30 +1,29 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-cmds=()
+# this is a simple config for herbstluftwm
 
 hc() {
-    cmds+=(";" "$@")
+    herbstclient "$@"
 }
 
 hc emit_hook reload
 
-xsetroot -solid '#222222'
+# remove all existing keybindings
 hc keyunbind --all
 
-#herbstclient detect_monitors
-hc detect_monitors
-#hc set_monitors 2560x1080+0+0 1680x1050+2560+0
-hc pad 0 30 0 30 0
-
+# keybindings
+# if you have a super key you will be much happier with Mod set to Mod4
+#Mod=Mod1    # Use alt as the main modifier
 Mod=Mod4   # Use the super key as the main modifier
 
-hc keybind $Mod-Shift-q close
+hc keybind $Mod-Shift-q quit
 hc keybind $Mod-Shift-r reload
-hc keybind $Mod-Shift-c close
-hc keybind $Mod-c       close_and_remove
-hc keybind $Mod-Return spawn ${TERMINAL:-terminator} # use your $TERMINAL with xterm as fallback
-hc keybind $Mod-Alt-l spawn dm-tool lock
+hc keybind $Mod-c close
+hc keybind $Mod-Return spawn ${TERMINAL:-xfce4-terminal} # use your $TERMINAL with xterm as fallback
+hc keybind $Mod-r spawn rofi -show drun
 
+# basic movement
+# focusing clients
 hc keybind $Mod-Left  focus left
 hc keybind $Mod-Down  focus down
 hc keybind $Mod-Up    focus up
@@ -34,26 +33,24 @@ hc keybind $Mod-j     focus down
 hc keybind $Mod-k     focus up
 hc keybind $Mod-l     focus right
 
+# moving clients
+hc keybind $Mod-Shift-h or / shift left / \
+    chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
+hc keybind $Mod-Shift-j or / shift down / \
+    chain , lock , shift_to_monitor -d , focus_monitor -d , unlock
+hc keybind $Mod-Shift-k or / shift up / \
+    chain , lock , shift_to_monitor -u , focus_monitor -u , unlock
+hc keybind $Mod-Shift-l or / shift right / \
+    chain , lock , shift_to_monitor -r , focus_monitor -r , unlock
 
-hc keybind $Mod-Shift-Left  shift left
-hc keybind $Mod-Shift-Down  shift down
-hc keybind $Mod-Shift-Up    shift up
-hc keybind $Mod-Shift-Right shift right
-hc keybind $Mod-Shift-h     shift left
-hc keybind $Mod-Shift-j     shift down
-hc keybind $Mod-Shift-k     shift up
-hc keybind $Mod-Shift-l     shift right
-
-
-hc keybind $Mod-u chain .-. split bottom 0.5 .-. focus down
-hc keybind $Mod-o chain .-. split right  0.5 .-. focus right
-
-hc keybind $Mod-Shift-u chain .-. split bottom 0.5 .-. shift_edge down
-hc keybind $Mod-Shift-o chain .-. split right  0.5 .-. shift_edge right
-
+# splitting frames
+# create an empty frame at the specified direction
+hc keybind $Mod-u       split   bottom  0.5
+hc keybind $Mod-o       split   right   0.5
+# let the current frame explode into subframes
 hc keybind $Mod-Control-space split explode
 
-
+# resizing frames
 resizestep=0.05
 hc keybind $Mod-Control-h       resize left +$resizestep
 hc keybind $Mod-Control-j       resize down +$resizestep
@@ -64,124 +61,174 @@ hc keybind $Mod-Control-Down    resize down +$resizestep
 hc keybind $Mod-Control-Up      resize up +$resizestep
 hc keybind $Mod-Control-Right   resize right +$resizestep
 
+
+# tags
+mon1_names=( 1_{1..5} ) # tag names for monitor 1
+mon2_names=( 2_{1..5} ) # tag names for monitor 2
+fallback_names=( {1..5} ) # tag names for all other monitors
+tag_keys=( {1..9} 0 )
+
+hc rename default "${mon1_names[0]}" || true
+for tag in "${mon1_names[@]}" "${mon2_names[@]}" "${fallback_names[@]}" ; do
+    hc try silent add "$tag"
+done
+
+for i in ${!tag_keys[@]} ; do
+    key="${tag_keys[$i]}"
+    # they kebinding is as follows: the or executes the commands seperated by
+    # CASE and stops executing them after the first of those succeeds.
+    # the first command is: check that we are on monitor 3 and can switch to tag "${mon1_names[$i]}"
+    # if only one of these to steps fail, try the second one (and so one).
+    # The setup for two monitors is as follows:
+    hc keybind "$Mod-$key" \
+        or CASE and . compare monitors.focus.index = 0 . use "${mon1_names[$i]}" \
+           CASE and . compare monitors.focus.index = 1 . use "${mon2_names[$i]}" \
+           CASE use "${fallback_names[$i]}"
+    hc keybind "$Mod-Shift-$key" \
+        or CASE and . compare monitors.focus.index = 0 . move "${mon1_names[$i]}" \
+           CASE and . compare monitors.focus.index = 1 . move "${mon2_names[$i]}" \
+           CASE move "${fallback_names[$i]}"
+done
+
+# cycle through tags
+# add additional information in order to cycle only through a monitor's tags
+# and not through all tags
+define-tag-cycle() {
+    local n=$#
+    local tags=( "$@" )
+    for i in "${!tags[@]}" ; do
+        local t="${tags[$i]}"
+        hc chain , new_attr string tags.by-name."$t".my_previous_tag \
+                 , set_attr tags.by-name."$t".my_previous_tag "${tags[$(((i - 1 + n) % n))]}" \
+                 , new_attr string tags.by-name."$t".my_next_tag \
+                 , set_attr tags.by-name."$t".my_next_tag "${tags[$(((i + 1) % n))]}"
+    done
+}
+
+define-tag-cycle "${mon1_names[@]}"
+define-tag-cycle "${mon2_names[@]}"
+define-tag-cycle "${fallback_names[@]}"
+
+# cycle through tags
+# check whether the current tag as a custom "next tag" configured
+# if yes, jump to that one, otherwise fall back to ordinary use_index +1
+hc keybind $Mod-period or , substitute NEXT tags.focus.my_next_tag use NEXT  \
+                          , use_index +1 --skip-visible
+hc keybind $Mod-comma  or , substitute PREV tags.focus.my_previous_tag use PREV  \
+                          , use_index +1 --skip-visible
+
+hc set swap_monitors_to_get_tag 0
+
+# tags
+# tag_names=( {1..9} )
+# tag_keys=( {1..9} 0 )
+# 
+# hc rename default "${tag_names[0]}" || true
+# for i in ${!tag_names[@]} ; do
+#   hc add "${tag_names[$i]}"
+#   key="${tag_keys[$i]}"
+#   if ! [ -z "$key" ] ; then
+#     hc keybind "$Mod-$key" use_index "$i"
+#     hc keybind "$Mod-Shift-$key" move_index "$i"
+#   fi
+# done
+
+# cycle through tags
 hc keybind $Mod-period use_index +1 --skip-visible
 hc keybind $Mod-comma  use_index -1 --skip-visible
 
-hc keybind $Mod-r remove
+# layouting
+hc keybind $Mod-q remove
 hc keybind $Mod-s floating toggle
 hc keybind $Mod-f fullscreen toggle
 hc keybind $Mod-p pseudotile toggle
-hc keybind $Mod-w set_layout max
-hc keybind $Mod-g set_layout grid
-hc keybind $Mod-v set_layout vertical
-hc keybind $Mod-a set_layout horizontal
-hc keybind $Mod-Shift-space cycle_layout
+# The following cycles through the available layouts within a frame, but skips
+# layouts, if the layout change wouldn't affect the actual window positions.
+# I.e. if there are two windows within a frame, the grid layout is skipped.
 hc keybind $Mod-space                                                           \
             or , and . compare tags.focus.curframe_wcount = 2                   \
                      . cycle_layout +1 vertical horizontal max vertical grid    \
                , cycle_layout +1
+
+# mouse
 hc mouseunbind --all
 hc mousebind $Mod-Button1 move
 hc mousebind $Mod-Button2 zoom
 hc mousebind $Mod-Button3 resize
+hc set focus_follows_mouse 1
 
-
+# focus
 hc keybind $Mod-BackSpace   cycle_monitor
 hc keybind $Mod-Tab         cycle_all +1
 hc keybind $Mod-Shift-Tab   cycle_all -1
+#hc keybind $Mod-c cycle
 hc keybind $Mod-i jumpto urgent
-hc keybind $Mod-d spawn rofi -show run
 
-
-# Volume
-hc keybind XF86AudioRaiseVolume spawn pulseaudio-ctl up
-hc keybind XF86AudioLowerVolume spawn pulseaudio-ctl down
-hc keybind XF86AudioMute spawn pulseaudio-ctl mute
-
-# Brightness
-
-hc keybind XF86MonBrightnessUp spawn xbacklight -inc 5
-hc keybind XF86MonBrightnessDown spawn xbacklight -dec 5
-
+# theme
 hc attr theme.tiling.reset 1
 hc attr theme.floating.reset 1
-hc set frame_border_active_color '#ff9933'
-hc set frame_border_normal_color '#322322'
-hc set frame_bg_normal_color '#292a44'
-hc set frame_bg_active_color '#292a44'
-hc set frame_border_width 2
-hc set always_show_frame 0
-hc set frame_active_opacity 0
-hc set frame_normal_opacity 0
+hc set frame_border_active_color '#E88A30'
+hc set frame_border_normal_color '#181818'
+hc set frame_bg_normal_color '#565656'
+hc set frame_bg_active_color '#345F0C'
+hc set frame_border_width 1
+hc set always_show_frame 1
+hc set frame_bg_transparent 1
 hc set frame_transparent_width 0
+hc set frame_gap 10
 
-hc attr theme.active.color '#ffffff'
-hc attr theme.normal.color '#000000'
-hc attr theme.urgent.color '#e72d2d'
+hc attr theme.active.color '#E88A30'
+hc attr theme.normal.color '#242424'
+hc attr theme.urgent.color '#D52B1D'
 hc attr theme.inner_width 0
 hc attr theme.inner_color black
-hc attr theme.border_width 0
-hc attr theme.floating.border_width 0
-hc attr theme.floating.outer_width 0
+hc attr theme.border_width 1
+hc attr theme.padding_left 7
+hc attr theme.floating.border_width 1
+hc attr theme.floating.outer_width 1
 hc attr theme.floating.outer_color black
 hc attr theme.active.inner_color '#3E4A00'
 hc attr theme.active.outer_color '#3E4A00'
 hc attr theme.background_color '#141414'
 
 hc set window_gap 0
-hc set window_padding 0
-hc set frame_gap 10
 hc set frame_padding 0
-hc set smart_window_surroundings 0
-hc set smart_frame_surroundings 0
+hc set smart_window_surroundings 1
+hc set smart_frame_surroundings 1
 hc set mouse_recenter_gap 0
 
-# tags (Font-Awesome)
-TAG_NAMES=( {"     ","     ","     ","     ","     ","     ","     ","     ","     "} )
-#TAG_NAMES=( {" WEB "," TERMINALS "," DEV "," MUSIC "," FILES "," CHAT "," VMs "," NEWS "," SCHOOL "," OTHER "} )
-TAG_KEYS=( {1..9} 0 )
-
-hc rename default "${TAG_NAMES[0]}" || true
-for i in ${!TAG_NAMES[@]} ; do
-    hc add "${TAG_NAMES[$i]}"
-    key="${TAG_KEYS[$i]}"
-    if ! [ -z "$key" ] ; then
-        hc keybind "$Mod-$key"        use_index "$i"
-        hc keybind "$Mod-Shift-$key" move_index "$i"
-    fi
-done
-
+# rules
 hc unrule -F
+#hc rule class=XTerm tag=3 # move all xterms to tag 3
 hc rule focus=on # normally focus new clients
+#hc rule focus=off # normally do not focus new clients
+# give focus to most common terminals
+#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
 hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
 hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
 hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
-hc rule class~'[Pp]olybar' manage=off
-hc rule class=Spotify tag=
-hc rule class=firefox tag=
 
+hc set tree_style '╾│ ├└╼─┐'
+
+# unlock, just to be sure
 hc unlock
 
-herbstclient chain "${cmds[@]}" &
+# do multi monitor setup here, e.g.:
+# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
+# or simply:
+hc detect_monitors
 
-herbstclient set tree_style '╾│ ├└╼─┐'
+# find the panel
+#panel=~/.config/herbstluftwm/panel.sh
+#[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
+#for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
+#    # start it on each monitor
+#    "$panel" $monitor &
+#
+#done
 
-pkill compton
-compton -b
-killall dunst
-dunst -conf /home/audron/.config/dunst/dunstrc &
-nitrogen --restore &
-xrdb .Xresources
-pkill polybar
-polybar top &
-polybar bot &
-pkill redshift
-redshift-gtk -t 5600K:3500K &
-xmodmap ~/.xmodmap &
-NetworkManager &
-nm-applet &
+hc pad 0 25
 
-if herbstclient silent new_attr bool my_not_first_autostart ; then
-    mopidy &
-fi
-
+killall -q polybar
+while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done
+polybar top -r &
